const MessageType = {
    FETCH_FILE_INFO: "FETCH_FILE_INFO",
    FETCH_FILE_INFO_RESPONSE: "FETCH_FILE_INFO_RESPONSE",
    FETCH_FILE_DATA: "FETCH_FILE_DATA",
    FETCH_FOLDER_LIST: "FETCH_FOLDER_LIST",
    FETCH_FOLDER_LIST_RESPONSE: "FETCH_FOLDER_LIST_RESPONSE",
    FETCH_FILE_LIST: "FETCH_FILE_LIST",
    FETCH_FILE_LIST_RESPONSE: "FETCH_FILE_LIST_RESPONSE"
};

const MessageStatus = {
    SUCCESS: "SUCCESS",
    FAILURE: "FAILURE",
    RECEIVED: "RECEIVED"
};

module.exports = {
    MessageType,
    MessageStatus
};